### ISSUE TITLE
 why do you choose Preemptive

### ISSUE THREAD

**Issue by HoangNgo88** [niedzielski/dkernel#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose preemptive in your project instead of cooperative multitasking, are there any special feature but others dont have Can you share me about it. I am wondering when I should choose preemptive in your project instead of cooperative multitasking

**Comment by niedzielski** [comment]
Great question! I think primarily because it was a learning exercise. My thought was probably that if I could successfully pause a running program, preserve and later restore its state seamlessly, I could also easily do cooperative multitasking. There may have been interrupt service routine concerns where a running user program could be preempted by the interrupt (I can't remember if this was configurable).

That said, I think this code is close to 17 years old and I haven't touched it since. I wrote this when I was a student studying embedded development and operating systems. This is actually only a backup of some prior state of my original code from a friend I had shared it with. My laptop was stolen and the final state of the code was regrettably lost in 2011.
